WiDi : Align & Add the Iframeserver Methods.
BZ: 104096

To accomodate all HWC interfaces , one new method has been added,
same has to be declared here to avoid compilation error for merrifield.

BufferInfoChanged needs to be called to trigger the clone mode pipeline.

Change-Id: Ic3cff0d16d67a8fd7dfd871985da69f8059068e4
Signed-off-by: Ashish Singhi <ashish.singhi@intel.com>
Reviewed-on: http://android.intel.com:8080/105174
Reviewed-by: cactus <cactus@intel.com>
Reviewed-by: Sun, Hang L <hang.l.sun@intel.com>
Reviewed-by: Crabtree, Robert <robert.crabtree@intel.com>
Tested-by: Post, DavidX J <davidx.j.post@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>